FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app
RUN uv pip install --system --no-cache google-genai chromadb google-cloud-storage python-dotenv gradio
COPY shared/ ./shared/
COPY main/ ./main/
COPY run_app.py ./
CMD ["python", "run_app.py"]